# action.yml
name: 'Ec2-start-stop'
description: 'Start and stop ec2'
inputs:
  AWS_REGION:  # id of input
    description: 'EC2 Region of EC2'
    required: true
  EC2_IDS:  # id of input
    description: 'Instance ids (comma seperated)'
    required: true
  AWS_EC2_ACTION:  # id of input
    description: 'start/stop'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  entrypoint: /bin/bash
  image: 'Dockerfile'